# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

tests:
test3.6
  stage: test
  script:
  - pip install -r requirements.txt
  - pytest tests

test3.7
  stage: test
  script:
  - source deactivate
  - virtualenv venv3.7 --python=python3.7
  - source venv3.7/bin/activate
  - pip install -r requirements.txt
  - pytest tests

test3.5
  stage: test
  script:
  - source deactivate
  - virtualenv venv3.5 --python=python3.5
  - source venv3.5/bin/activate
  - pip install -r requirements.txt
  - pytest tests




